version: '2'
services:
  pluma-postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/Pluma/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=Pluma
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
